version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  archivos_compartidos: {}

services:
  web_server: &pythonbuild
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./compose/web-server/Dockerfile
    image: api-cluster-one-web-server
    volumes:
      - .:/app
      - archivos_compartidos:/app/app/media/
    env_file:
      - ./.env
    environment:
      - DEBUG=True
    ports:
      - "8203:8000"
    depends_on:
      - db
    command: uvicorn app.web_server:app --reload --host 0.0.0.0 --log-level debug

  redis:
    image: redis:5.0
    ports:
      - "6379:6379"

  db:
    build:
      context: .
      dockerfile: ./compose/db/Dockerfile
    image: api-cluster-one-db
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  celeryworker:
    platform: "linux/amd64"
    image: api-cluster-one-web_celeryworker
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - archivos_compartidos:/app/app/media/
    build:
      context: .
      dockerfile: ./compose/web-server/Dockerfile
    command: [ "./start-celeryworker" ]

  celerybeat:
    platform: "linux/amd64"
    image: api-cluster-one-web_celerybeat
    depends_on:
      - redis
      - db
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./compose/web-server/Dockerfile
    command: [ "./start-celerybeat" ]
  # flower:
  #   platform: "linux/amd64"
  #   image: api-cluster-one-web_flower
  #   ports:
  #     - "5555:5555"
  #   env_file:
  #     - .env
  #   build:
  #     context: .
  #     dockerfile: ./compose/web-server/Dockerfile
  #   command: [ "./start-flower" ]
