"""Add weighted band in PPIgraph nullable

Revision ID: 126f8f8bda85
Revises: b694e833156f
Create Date: 2024-05-30 21:59:15.662645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126f8f8bda85'
down_revision = 'b694e833156f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppi_graph', sa.Column('weighted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppi_graph', 'weighted')
    # ### end Alembic commands ###
