"""Create Proteome Model

Revision ID: 2e120b591fcc
Revises: 5c9e7b0f5f1f
Create Date: 2023-10-27 04:56:14.922539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e120b591fcc'
down_revision = '5c9e7b0f5f1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
