"""Add cluster one logs params

Revision ID: 456cc4cca341
Revises: 63194f807944
Create Date: 2023-09-25 06:48:10.681258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456cc4cca341'
down_revision = '63194f807944'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_one_log_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_size', sa.Integer(), nullable=True),
    sa.Column('min_density', sa.Float(), nullable=True),
    sa.Column('max_overlap', sa.Float(), nullable=True),
    sa.Column('penalty', sa.Float(), nullable=True),
    sa.Column('ppi_graph_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ppi_graph_id'], ['ppi_graph.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('min_size', 'min_density', 'max_overlap', 'penalty', 'ppi_graph_id')
    )
    op.create_index(op.f('ix_cluster_one_log_params_id'), 'cluster_one_log_params', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_one_log_params_id'), table_name='cluster_one_log_params')
    op.drop_table('cluster_one_log_params')
    # ### end Alembic commands ###
