"""Update Cluster Model

Revision ID: 5094d3203ecd
Revises: 456cc4cca341
Create Date: 2023-09-25 06:49:22.629469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5094d3203ecd'
down_revision = '456cc4cca341'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_graph', sa.Column('cluster_one_log_params_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cluster_graph', 'cluster_one_log_params', ['cluster_one_log_params_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cluster_graph', type_='foreignkey')
    op.drop_column('cluster_graph', 'cluster_one_log_params_id')
    # ### end Alembic commands ###
