"""Update ClusterOneLog model

Revision ID: 5c9e7b0f5f1f
Revises: 5094d3203ecd
Create Date: 2023-09-27 02:43:52.753396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9e7b0f5f1f'
down_revision = '5094d3203ecd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
