"""me colgue

Revision ID: 62658394cffa
Revises: 6d16318a340a
Create Date: 2023-11-04 20:12:43.465772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62658394cffa'
down_revision = '6d16318a340a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_graph', sa.Column('data_file_id', sa.Integer(), nullable=True))
    op.add_column('protein', sa.Column('uniprotkb_id', sa.Float(), nullable=True))
    op.drop_column('protein', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protein', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('protein', 'uniprotkb_id')
    op.drop_column('cluster_graph', 'data_file_id')
    # ### end Alembic commands ###
