"""Change model name and table name

Revision ID: 63194f807944
Revises: c46eb9225868
Create Date: 2023-09-08 01:39:21.517782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63194f807944'
down_revision = 'c46eb9225868'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overlapping_protein',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url_info', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cluster_graph_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_graph_id'], ['cluster_graph.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overlapping_protein_id'), 'overlapping_protein', ['id'], unique=False)
    op.drop_index('ix_protein_complex_id', table_name='protein_complex')
    op.drop_table('protein_complex')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protein_complex',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_important', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cluster_graph_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cluster_graph_id'], ['cluster_graph.id'], name='protein_complex_cluster_graph_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='protein_complex_pkey')
    )
    op.create_index('ix_protein_complex_id', 'protein_complex', ['id'], unique=False)
    op.drop_index(op.f('ix_overlapping_protein_id'), table_name='overlapping_protein')
    op.drop_table('overlapping_protein')
    # ### end Alembic commands ###
