"""Delete Unsued Field

Revision ID: 6476f1089531
Revises: 9ff110700fee
Create Date: 2023-10-30 21:01:27.952024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6476f1089531'
down_revision = '9ff110700fee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrichment', 'is_important')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrichment', sa.Column('is_important', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
