"""Add State into enrichmenta

Revision ID: 6d16318a340a
Revises: 6476f1089531
Create Date: 2023-10-30 21:09:32.734871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d16318a340a'
down_revision = '6476f1089531'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrichment', sa.Column('state', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrichment', 'state')
    # ### end Alembic commands ###
