"""Add proteome FK into ppi graph

Revision ID: 735f89b1efdc
Revises: cc8b1ce81dd8
Create Date: 2023-10-27 05:13:15.221669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735f89b1efdc'
down_revision = 'cc8b1ce81dd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppi_graph', sa.Column('proteome_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ppi_graph', 'proteome', ['proteome_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ppi_graph', type_='foreignkey')
    op.drop_column('ppi_graph', 'proteome_id')
    # ### end Alembic commands ###
