"""Add boolean field to indicate if cluster is complex

Revision ID: a393d6521a38
Revises: 91ff7268e1cd
Create Date: 2023-06-07 06:31:08.039277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a393d6521a38'
down_revision = '91ff7268e1cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_graph', sa.Column('is_complex', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_graph', 'is_complex')
    # ### end Alembic commands ###
