"""Delete UnUsed field in cluster_graph

Revision ID: b57d3c911bcd
Revises: ed8807f828c1
Create Date: 2023-11-07 20:52:55.250599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57d3c911bcd'
down_revision = 'ed8807f828c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cluster_graph_enrichment_id_fkey', 'cluster_graph', type_='foreignkey')
    op.drop_column('cluster_graph', 'enrichment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_graph', sa.Column('enrichment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cluster_graph_enrichment_id_fkey', 'cluster_graph', 'enrichment', ['enrichment_id'], ['id'])
    # ### end Alembic commands ###
