"""Add ORA Score Into ClusterOneLog params

Revision ID: b694e833156f
Revises: b57d3c911bcd
Create Date: 2023-11-16 04:39:40.678513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b694e833156f'
down_revision = 'b57d3c911bcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_one_log_params', sa.Column('ora_bp_score', sa.Float(), nullable=True))
    op.add_column('cluster_one_log_params', sa.Column('ora_cc_score', sa.Float(), nullable=True))
    op.add_column('cluster_one_log_params', sa.Column('ora_mf_score', sa.Float(), nullable=True))
    op.drop_column('overlapping_protein', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overlapping_protein', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('cluster_one_log_params', 'ora_mf_score')
    op.drop_column('cluster_one_log_params', 'ora_cc_score')
    op.drop_column('cluster_one_log_params', 'ora_bp_score')
    # ### end Alembic commands ###
