"""Create Proteome Model real

Revision ID: cc8b1ce81dd8
Revises: 2e120b591fcc
Create Date: 2023-10-27 04:58:32.715985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8b1ce81dd8'
down_revision = '2e120b591fcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proteome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url_info', sa.String(length=255), nullable=True),
    sa.Column('fasta_file_path', sa.String(length=255), nullable=True),
    sa.Column('uniprot_proteome_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proteome_id'), 'proteome', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proteome_id'), table_name='proteome')
    op.drop_table('proteome')
    # ### end Alembic commands ###
