"""Add data file path for ppi

Revision ID: eb7b5f560892
Revises: b0963f1e98c9
Create Date: 2023-06-05 00:57:28.580779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb7b5f560892"
down_revision = "b0963f1e98c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ppi_graph", sa.Column("data", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ppi_graph", "data")
    # ### end Alembic commands ###
