"""Add go id and delete name in Enrichment

Revision ID: ed8807f828c1
Revises: 8add943961ff
Create Date: 2023-11-07 05:37:39.058667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8807f828c1'
down_revision = '8add943961ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrichment', 'name')
    op.add_column('go_terms', sa.Column('go_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('go_terms', 'go_id')
    op.add_column('enrichment', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
